/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReplayRouteImport } from './routes/app.replay'
import { Route as AppNodesRouteImport } from './routes/app.nodes'
import { Route as AppMeshRouteImport } from './routes/app.mesh'
import { Route as AppLivePortRouteImport } from './routes/app.live-port'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppGatewayRouteImport } from './routes/app.gateway'
import { Route as AppContainersRouteImport } from './routes/app.containers'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as ApiPublicGatewayQueueRouteImport } from './routes/api/public/gateway/queue'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReplayRoute = AppReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesRoute = AppNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AppRoute,
} as any)
const AppMeshRoute = AppMeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => AppRoute,
} as any)
const AppLivePortRoute = AppLivePortRouteImport.update({
  id: '/live-port',
  path: '/live-port',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppGatewayRoute = AppGatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => AppRoute,
} as any)
const AppContainersRoute = AppContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicGatewayQueueRoute = ApiPublicGatewayQueueRouteImport.update({
  id: '/api/public/gateway/queue',
  path: '/api/public/gateway/queue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/containers': typeof AppContainersRoute
  '/app/gateway': typeof AppGatewayRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/live-port': typeof AppLivePortRoute
  '/app/mesh': typeof AppMeshRoute
  '/app/nodes': typeof AppNodesRoute
  '/app/replay': typeof AppReplayRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/gateway/queue': typeof ApiPublicGatewayQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/containers': typeof AppContainersRoute
  '/app/gateway': typeof AppGatewayRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/live-port': typeof AppLivePortRoute
  '/app/mesh': typeof AppMeshRoute
  '/app/nodes': typeof AppNodesRoute
  '/app/replay': typeof AppReplayRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/public/gateway/queue': typeof ApiPublicGatewayQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/containers': typeof AppContainersRoute
  '/app/gateway': typeof AppGatewayRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/live-port': typeof AppLivePortRoute
  '/app/mesh': typeof AppMeshRoute
  '/app/nodes': typeof AppNodesRoute
  '/app/replay': typeof AppReplayRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/gateway/queue': typeof ApiPublicGatewayQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ai'
    | '/app/analytics'
    | '/app/containers'
    | '/app/gateway'
    | '/app/incidents'
    | '/app/live-port'
    | '/app/mesh'
    | '/app/nodes'
    | '/app/replay'
    | '/app/settings'
    | '/app/'
    | '/api/public/gateway/queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/ai'
    | '/app/analytics'
    | '/app/containers'
    | '/app/gateway'
    | '/app/incidents'
    | '/app/live-port'
    | '/app/mesh'
    | '/app/nodes'
    | '/app/replay'
    | '/app/settings'
    | '/app'
    | '/api/public/gateway/queue'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ai'
    | '/app/analytics'
    | '/app/containers'
    | '/app/gateway'
    | '/app/incidents'
    | '/app/live-port'
    | '/app/mesh'
    | '/app/nodes'
    | '/app/replay'
    | '/app/settings'
    | '/app/'
    | '/api/public/gateway/queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiPublicGatewayQueueRoute: typeof ApiPublicGatewayQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/replay': {
      id: '/app/replay'
      path: '/replay'
      fullPath: '/app/replay'
      preLoaderRoute: typeof AppReplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nodes': {
      id: '/app/nodes'
      path: '/nodes'
      fullPath: '/app/nodes'
      preLoaderRoute: typeof AppNodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mesh': {
      id: '/app/mesh'
      path: '/mesh'
      fullPath: '/app/mesh'
      preLoaderRoute: typeof AppMeshRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live-port': {
      id: '/app/live-port'
      path: '/live-port'
      fullPath: '/app/live-port'
      preLoaderRoute: typeof AppLivePortRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gateway': {
      id: '/app/gateway'
      path: '/gateway'
      fullPath: '/app/gateway'
      preLoaderRoute: typeof AppGatewayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/containers': {
      id: '/app/containers'
      path: '/containers'
      fullPath: '/app/containers'
      preLoaderRoute: typeof AppContainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/gateway/queue': {
      id: '/api/public/gateway/queue'
      path: '/api/public/gateway/queue'
      fullPath: '/api/public/gateway/queue'
      preLoaderRoute: typeof ApiPublicGatewayQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppContainersRoute: typeof AppContainersRoute
  AppGatewayRoute: typeof AppGatewayRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppLivePortRoute: typeof AppLivePortRoute
  AppMeshRoute: typeof AppMeshRoute
  AppNodesRoute: typeof AppNodesRoute
  AppReplayRoute: typeof AppReplayRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppContainersRoute: AppContainersRoute,
  AppGatewayRoute: AppGatewayRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppLivePortRoute: AppLivePortRoute,
  AppMeshRoute: AppMeshRoute,
  AppNodesRoute: AppNodesRoute,
  AppReplayRoute: AppReplayRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiPublicGatewayQueueRoute: ApiPublicGatewayQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
